### ISSUE TITLE
Fix logic in copy_config_vars.py

### ISSUE THREAD

**Issue by dasanchez** [hyphacoop/cosmos-ansible#148]
The `set_nested` function in `copy_config_vars.py` allows me to add a key to a config file.

If I use the variables template to add a non-existent `client-version` section to `client.toml`, the resulting config will crop the section, which is incorrect.

### `ansible_vars.json.j2`
```
{
"client.toml": {
    "keyring-backend": {{ client_keyring_backend | to_json }},
    "broadcast-mode": {{ client_broadcast_mode | to_json }},
    "client-version.patch": "5"
...
```

the resulting config file will be:
### `client.toml`
```
chain-id = "offline-testnet"
keyring-backend = "os"
output = "text"
node = "tcp://localhost:26657"
broadcast-mode = "sync"
patch = "5"

```
To reproduce:
- Modify `ansible_vars.json.j2` as shown above
- Use `examples/inventory-local.yml` to deploy a local testnet
- Check the `config/client.toml` file

**Comment by makeworld-the-better-one** [comment]
Desired outcome is:

```toml
chain-id = "offline-testnet"
keyring-backend = "os"
output = "text"
node = "tcp://localhost:26657"
broadcast-mode = "sync"
[client-version]
patch = "5"
```
