### ISSUE TITLE
Ansible hangs/failes during validator creation 

### ISSUE THREAD

**Issue by YurkoWasHere** [hyphacoop/cosmos-ansible#162]
When `chain_home_clear` is not set to true create validator steps fails

Possible should have checks define what tasks are available during chain creation only, and check against `chain_home_clear` as well?

**Comment by dasanchez** [comment]
Can you post the error message and how to reach the failure point please?
I would like to replicate the error, but commenting `gaiad_home_autoclear` or `chain_home_clear` works for me.

## Using the `main` branch
- Fresh Ubuntu 22.04 VM
- Blocks are produced
```
---
# yamllint disable rule:line-length
all:
  vars:
    # gaiad_home_autoclear: true
    gaiad_version: v7.0.0
    gaiad_create_validator: true
    faucet_enabled: true
    ansible_user: root
  children:
    gaia:
      hosts:
        "{{ target }}":
          fast_sync: false
          chain_id: my-testnet
```

## Using the `feature/129-agnostic-role` branch
- Fresh Ubuntu 22.04 VM
- Blocks are produced
```
# yamllint disable rule:line-length
all:
  vars:
    # chain_home_clear: true
    chain_version: v7.0.0
    chain_create_validator: true
    faucet_enabled: true
    ansible_user: root
  children:
    node:
      hosts:
        "{{ target }}":
          fast_sync: false
          chain_id: my-testnet
```

**Comment by YurkoWasHere** [comment]
currently it hangs on create-validator
```
TASK [gaia : create validator] *************************************************
```

But before it would crash after a long wait on

```
- name: collect gentx
```


Offending inventory file i used
```
# yamllint disable rule:line-length
all:
  vars:
    ansible_user: sysadmin

    rust_user: "{{node_user}}"
    node_home_autoclear: false
    node_unsafe_reset: false
    node_use_ssl_proxy: false
    chain_create_validator: true
    node_home_clear: true
    node_api_host: "rest"
    node_rpc_host: "rpc"
    node_p2p_host: "p2p"
    node_grpc_host: "grpc"
    minimum_gas_prices: "0.0025uatom"
    use_cosmovisor: true
  children:
    gaia:
      hosts:
        "testnet.cosmos.hypha.coop":

```
