### ISSUE TITLE
Add faucet_start variable to faucet role

### ISSUE THREAD

**Issue by dasanchez** [hyphacoop/cosmos-ansible#331]
We may want to defer the start of the faucet service to after the play runs:
```
- name: Start faucet service
  systemd:
    daemon_reload: true
    state: restarted
    enabled: true
    name: "{{faucet_service_name}}"
  tags:
    - faucet_start
    - faucet_restart
  when: (faucet_start | default(false) | bool)
```
