### ISSUE TITLE
Running playbook without a genesis file fails

### ISSUE THREAD

**Issue by dasanchez** [hyphacoop/cosmos-ansible#49]
I ran this playbook:
```
---
# yamllint disable rule:line-length
all:
  vars:
    gaiad_home_autoclear: true
    gaiad_version: v7.0.0
    api_enabled: true
    chain_id: "test-devnet"
    gaiad_use_ssl_proxy: true
    gaiad_api_host: "rest"
    gaiad_rpc_host: "rpc"
    letsencrypt_email: "my-email"
    enable_swap: false
    swap_size: 8192
    reboot: false
  children:
    gaia:
      hosts:
        my-host-address:
          ansible_user: root
          gaiad_create_validator: true
```
And got this error:
```
TASK [gaia : File type of {{genesis_file}}] *********************************************************************************************************************
fatal: [my-host-address]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'stat'
```
It could be [this task](https://github.com/hyphacoop/cosmos-ansible/blob/844f0112644066228829eb71314e2129cd2cc0cd/roles/gaia/tasks/main.yml#L207) needs a `when:` field.
